version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  be-api:
    depends_on:
      - mysqldb
    build: ./be-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      #- $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - 8080:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      #- CLIENT_ORIGIN=$CLIENT_ORIGIN
      - CLIENT_ORIGIN=http://127.0.0.1:8081
    networks:
      - backend

  ui:
    depends_on:
      - be-api
    build:
      context: ./ui
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:8080/api
    ports:
      - 3000:8081
    networks:
      - frontend
volumes:
  db:
networks:
  frontend:
  backend:
