version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --init-file /data/application/init.sql
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - backend

  backend:
    depends_on:
      - mysqldb
    build: ./be1
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - SECRET_KEY=$BACKEND_SECRET_KEY
      # - CLIENT_ORIGIN=$CLIENT_ORIGIN
      # - CLIENT_ORIGIN=http://127.0.0.1:8081
    stdin_open: true
    tty: true
    networks:
      - backend
  # frontend:
  #   depends_on:
  #      - be-api
  #   build:
  #     context: ./ui
  #     args:
  #       - REACT_APP_API_BASE_URL=http://127.0.0.1:8080/api
  #   ports:
  #     - 3000:8081
  #   networks:
  #     - frontend
volumes:
  db: 
networks:
  # frontend:
  backend:  
