version: '3.7'
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./:/backend
    ports: 
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: chatdemoapp
    links:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - chatapp-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatdemoapp
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8000:8000
    links:
      - backend
volumes:
  chatapp-data:

  
   